# Generated by Django 2.0.5 on 2018-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_personnel_treeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='photo',
        ),
        migrations.AddField(
            model_name='personnel',
            name='photos_address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
