# Generated by Django 2.0.5 on 2018-06-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180608_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='photos',
        ),
    ]
