# Generated by Django 2.0.5 on 2018-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_personnel_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_num', models.CharField(max_length=20)),
                ('seed_name', models.CharField(max_length=20)),
                ('ke_name', models.CharField(blank=True, max_length=20, null=True)),
                ('shu_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ya_name', models.CharField(blank=True, max_length=20, null=True)),
                ('seed_image', models.CharField(blank=True, max_length=60, null=True)),
                ('character', models.CharField(blank=True, max_length=50, null=True)),
                ('main_use', models.CharField(blank=True, max_length=30, null=True)),
                ('climate', models.CharField(blank=True, max_length=30, null=True)),
                ('live', models.TextField(blank=True, null=True)),
                ('flower', models.CharField(blank=True, max_length=40, null=True)),
                ('feature', models.TextField(blank=True, null=True)),
                ('seed_use', models.TextField(blank=True, null=True)),
                ('watch_place', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('grow_year', models.CharField(blank=True, max_length=20, null=True)),
                ('save_year', models.CharField(blank=True, max_length=20, null=True)),
                ('altitude', models.CharField(blank=True, max_length=10, null=True)),
                ('podu', models.CharField(blank=True, max_length=20, null=True)),
                ('poxiang', models.CharField(blank=True, max_length=20, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=30, null=True)),
                ('gps_x', models.CharField(blank=True, max_length=30, null=True)),
                ('gps_y', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('auditor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='TreeInfo',
        ),
    ]
